# Site settings
title: 'GROK'
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://bopoh13.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: '/jekyll-uno' # the subpath of your site, e.g. /blog
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

remote_theme: matthiaslischka/jekyll-uno

author:
  name: 'bopoh13'
  #email: 
  #twitter_username: 
  #facebook_username: 
  github_username: bopoh13
  #linkedin_username:  

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

#sass:
#    sass_dir: _sass
#    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

plugins:
#  - jekyll-paginate
  - jekyll-remote-theme
#  - jekyll-include-cache
  
#exclude: ['README.md', 'Gemfile', 'Gemfile.lock', '.travis.yml', 'vendor']
